# Generated by Django 3.2.6 on 2021-08-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('family_info', models.TextField(blank=True)),
                ('tests', models.CharField(choices=[('PCR', 'PCR'), ('Antigen', 'Antigen')], max_length=50)),
            ],
        ),
    ]
