# Generated by Django 3.2.6 on 2021-08-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210815_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_status',
            field=models.CharField(choices=[('Tested Positive', 'Positive'), ('Quarntined', 'Qurantined'), ('Dead', 'Dead')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
    ]
